# Generated by Django 3.1.7 on 2021-02-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
    ]
